### PR TITLE
fix/refactor(front): Put GraphQL query statement into `newsSlice`, etc.

### PR DESCRIPTION
**Pull request by PeterlitsZo**
Put these statements as hooks into `newsSlice.ts`, and make sure they match to the definetion of the backend.

### CODE REVIEW

**Review by TTL2000 — APPROVED** [review]

**Comment by PeterlitsZo** [comment]
WIP, do not rebase please.

**Comment by PeterlitsZo** [comment]
Done. Please review.

**Comment by PeterlitsZo** [comment]
:eyes:

**Review by RileyYe — COMMENTED** [review]
No problem

**Review by TTL2000 — APPROVED** [review]
OK

**Pull request merged**
