### PR TITLE
Refactor graphql query and mutation

### PR DESCRIPTION
**Pull request by PeterlitsZo**
I hope it will make the back-end more clear than before!

### CODE REVIEW

**Review by RileyYe — APPROVED** [review]
Excellent idea.

**Comment by PeterlitsZo** [comment]
It will be better if you use TypeScript to make sure the `QueryField` and `MutationField`'s key is right.

I hope we can try to use it after two weeks or one month.

**Comment by RileyYe** [comment]
> It will be better if you use TypeScript to make sure the `QueryField` and `MutationField`'s key is right.
> 
> I hope we can try to use it after two weeks or one month.

**Comment by PeterlitsZo** [comment]
:sob:

**Comment by RileyYe** [comment]
The key of `QueryField` and `MutationField` is not so complex. Switching to TS may be optional but not compulsory.

**Review by TTL2000 — APPROVED** [review]

**Pull request merged**
