### PR TITLE
docs: Add PR check list.

### PR DESCRIPTION
**Pull request by PeterlitsZo**
Remember: Also change the Github's PR template.

### CODE REVIEW

**Comment by RileyYe** [comment]
No problem, approved

**Comment by PeterlitsZo** [comment]
Please wait for @TTL2000 .

**Comment by PeterlitsZo** [comment]
How to create PR template: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

WIP.

**Review by TTL2000 — APPROVED** [review]

**Comment by PeterlitsZo** [comment]
Please review. The last reviewer should rebase it please.

**Comment by PeterlitsZo** [comment]
:eyes:

**Review by TTL2000 — APPROVED** [review]

**Review by TTL2000 — APPROVED** [review]

**Pull request merged**
