### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by PeterlitsZo**
Let PRer tell us what he/she did.

Hello! Welcome to send a PR to us! Here is a simple PR checklist:

- [x] Format your code, by `yarn format`. Good format is helpful for everyone.
- [x] (NOT NOW) Make sure tests are passed.
- [x] If you need update document, then update. The documents are here:
  - `README.md` in the root folder of project, about what the project is and
    why the project exists.
  - `README.md` in the `back` or `front` folder.
  - In `docs` folder, there are the other documents.

### CODE REVIEW

**Comment by PeterlitsZo** [comment]
What else do you think that we should put into the PR template?

**Comment by PeterlitsZo** [comment]
I think that ask PRer format their PR title is a good idea. Do you think so?

**Comment by RileyYe** [comment]
I think it's ok to let commit titles be pr titles

**Review by TTL2000 — APPROVED** [review]

**Comment by PeterlitsZo** [comment]
> I think it's OK to let commit titles be pr titles.

But... What will happen if PR has a lot of commit nodes? Or you mean that tell them have the same style?

**Comment by PeterlitsZo** [comment]
@RileyYe

**Comment by PeterlitsZo** [comment]
Well...

**Comment by PeterlitsZo** [comment]
I cannot wait for another 7 days.

**Pull request merged**
