### PR TITLE
docs: Add rule on how to add URLs in the git message body.

### PR DESCRIPTION
**Pull request by PeterlitsZo**
Hello! Welcome to send a PR to us! Here is a simple PR checklist:

- [x] Format your code, by `yarn format`. Good format is helpful for everyone.
- [x] (NOT NOW) Make sure tests are passed.
- [x] If you need update document, then update. The documents are here:
  - `README.md` in the root folder of project, about what the project is and
    why the project exists.
  - `README.md` in the `back` or `front` folder.
  - In `docs` folder, there are the other documents.

### CODE REVIEW

**Comment by PeterlitsZo** [comment]
Do you have a better idea?

**Comment by RileyYe** [comment]
What about considering the url a kind of reference, so we use it this way:

// Git Messages
> www.google.com

// Git Messages

**A example is:**
----

I reset it to 8k, because larger buffer size would ease DDoS attack vectors.
For more information, see :
> https://stackoverflow.com/questions/35005130/nginx-client-body-buffer-size-and-client-max-body-size-optimizations-for-large-p

.
----
Here I will list the reasons.

1.  We will try to make the commit message clean and strive to make it straight-forward. If we apply the Markdown referecce links ([emphasis tutorials][myexample]) on the commit message, it will make the message hard to read. The reader will only want to acquire the reference link imediately when he knows there was a reference.  If we use Markdown referecce links, when the scale of links and commit message grows up, it will be very hard  to read (It may cost longer time for reader to pick out the one from a list of urls, unless the urls is ordered by their names, which may also make drafting commit messages harder if we are supposed to arrange the urls by hands).
2. When we use `git log -a` command in a console, the message shows by lines. We won't get the links imediately in this case.
3. For most cases, the commit message is shown on a console. So it won't be rendered even if it's written in Markdown. It is very critical to make commit message not intricate.
4. Linus said, `we use 72-character columns for word-wrapping, except for quoted material that has a specific line format.`
See: https://github.com/torvalds/linux/pull/17#issuecomment-5661185 .

**Comment by PeterlitsZo** [comment]
Should we also use 72 characters rather than 80 characters in title and body?

**Comment by RileyYe** [comment]
80 chars in each line is ok I think.

**Comment by PeterlitsZo** [comment]
I think use `>` sign for URL is good idea.

By the way, even trough we show git message in plain text mode (for example, me), it is clear enough for reader. And reader can also use his/her tool to search in the message.

And we do not need to get the link immediately. And if the message is too large, in my opinion, it's time to split that commit into a lot of commits.

I never render markdown (I cannot because my editor is fucking vim). And markdown is clearly than you think.

**Comment by PeterlitsZo** [comment]
https://cbea.ms/git-commit/

Do you read this? I think it is good...

**Comment by PeterlitsZo** [comment]
May be
```
Docs: Add rule on how to add URLs in the git message body
```

is better than:
```
docs: Add rule on how to add URLs in the git message body.
```

When git create a merged commit node, its title is:
```
Merge branch '<name>' into <name>
```

So make the first character uppercase and remove the dot at the end is better (?).

**Comment by PeterlitsZo** [comment]
> 80 chars in each line is ok I think.

OK.

**Comment by RileyYe** [comment]
I prefer no period in the titles.


> May be
> 
> ```
> 
> Docs: Add rule on how to add URLs in the git message body
> 
> ```
> 
> 
> 
> is better than:
> 
> ```
> 
> docs: Add rule on how to add URLs in the git message body.
> 
> ```
> 
> 
> 
> When git create a merged commit node, its title is:
> 
> ```
> 
> Merge branch '<name>' into <name>
> 
> ```
> 
> 
> 
> So make the first character uppercase and remove the dot at the end is better (?).

**Review by TTL2000 — APPROVED** [review]

**Comment by PeterlitsZo** [comment]
OK. Could you push new change to [**my** branch](https://github.com/PeterlitsZo/ACMHomepage/tree/update-git-commit-message-rule)

**Comment by RileyYe** [comment]
Can I?

**Comment by PeterlitsZo** [comment]
> Can I?

Of course  :)

**Comment by PeterlitsZo** [comment]
This is my most recent commit. Would you like it?

**Comment by PeterlitsZo** [comment]
Close. See #20.

**Pull request closed without merging**
